# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/NINE-J"

[social.params]
icon = "brand-github"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"

[[social]]
identifier = "stackoverflow"
name = "StackOverflow"
url = "https://stackoverflow.com/users/17334807/nine"

[social.params]
icon = "brand-stackoverflow"

[[social]]
identifier = "mail"
name = "ZMail"
url = "mailto:rnwo47@gmail.com"

[social.params]
icon = "mail"
